- name: Prepare webservers
  hosts: all
  gather_facts: yes
  remote_user: root
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes
    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker
    - name: Create .env
      ansible.builtin.template:
        src: 'env.j2'
        dest: '.env'
        mode: 0664

- name: Deploy application
  hosts: all
  gather_facts: yes
  remote_user: root
  tasks:
    - name: Run container
      community.docker.docker_container:
        name: Redmine
        image: redmine
        restart_policy: always
        published_ports:
          - 3000:3000
        env_file: '.env'

- name: Datadog http check
  hosts: all
  roles:
    - { role: datadog.datadog, become: yes }
