- name: Prepare webservers
  hosts: all
  gather_facts: yes
  remote_user: root
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes
    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker
    - name: Create .env
      ansible.builtin.template:
        src: 'env.j2'
        dest: '.env'
        mode: 0664

- name: Deploy application
  hosts: all
  gather_facts: yes
  remote_user: root
  tasks:
    - name: Run container
      community.docker.docker_container:
        name: Redmine
        image: redmine
        restart_policy: always
        published_ports:
          - 3000:3000
        env_file: '.env'

- name: Datadog
  hosts: all
  gather_facts: yes
  remote_user: root
  vars_files:
    - "./group_vars/webservers/vars.yml"
  vars:
    app_port: "3000"
    datadog_api_key: '{{ datadog_api_key }}'
    datadog_site: "datadoghq.com"
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: Application health check status
            url: "http://devops-and1.club:{{ app_port }}"
            timeout: 5
            method: GET
  roles:
    - { role: datadog.datadog, become: yes }
